name: Jekyll Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      # 3. Install dependencies
      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle install

      # 4. Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site   # folder output Jekyll
